In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [3]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-05-06 13:47:34.955913
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-05-06 13:47:34.955913
2  10003    PREGO  BT12    100     60  z0019_2.csv 2026-05-06 13:47:34.955913

In [119]:
con.execute("""
create table if not exists bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_arquivo VARCHAR,
            data_ingestao TIMESTAMP
            )
""")

In [120]:
con.execute("INSERT INTO bronze_produtos SELECT * FROM df")

In [ ]:
resultado = con.execute("select * from bronze_produtos").fetchdf()
resultado.head()

In [7]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_Z0019")

In [16]:
resultado = con.execute("select * from bronze_Z0019").fetchdf()
resultado.head()

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100      z0019_1 2026-04-30 05:44:49.138360
1  10002   MARTELO  BT50   100  1500      z0019_1 2026-04-30 05:44:49.138360
2  10003     PREGO  BT10   100    50      z0019_1 2026-04-30 05:44:49.138360
3  10001  PARAFUSO  BT10   100   100      z0019_1 2026-04-30 05:44:49.138360
4  10002   MARTELO  BT50   100  1500      z0019_1 2026-04-30 05:44:49.138360

In [17]:
con.close()